chat/urls.py
from django.urls import path

from .views import home, signup_view, signin_view, room, signout_view, image_upload_view

app_name = 'chat'

urlpatterns = [
    path('', home, name='home'),
    path('room/<str:room_name>/', room, name='room'),
    path('signup/', signup_view, name='signup_namespace'),
    path('signin/', signin_view, name='signin_namespace'),
    path('signout/', signout_view, name='logout_namespace'),
    path('room/<str:room_name>/image_upload/', image_upload_view),
]

# path('upload/', mongo_image_upload),
# path('<str:room_name>/upload/', mongo_image_upload),

core/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('chat.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

chat/models.py
import datetime
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.template.defaultfilters import slugify 


class Messages(models.Model):
    user = models.ForeignKey(User, on_delete = models.CASCADE) # blank=True # blank = True is used when system need to give some empty string '' to match the other fields... Its's mainly used when system need to give some data.
    message = models.CharField(max_length = 50)
    created_on = models.DateTimeField(auto_now_add=True)
    room = models.ForeignKey(
        'Room', on_delete=models.CASCADE
    )
    image = models.ForeignKey(
        "ImageUpload", on_delete=models.CASCADE, blank=True, null=True
    )

    class Meta:
        ordering = ['-created_on']

    def __str__(self):
        return f"{self.user} | {self.room} | {self.image} | {self.message}"


class Room(models.Model):
    name = models.CharField(max_length=250, blank=True)
    room_slug = models.SlugField(null=True, unique=True)

    def __str__(self):
        return f"{self.name}"

    def save(self, *args, **kwargs):
        # to create a slug field to use in URL's
        if not self.room_slug:
            self.room_slug = slugify(self.name)
        return super().save(*args, **kwargs)


class ImageUpload(models.Model):
    # user = models.ForeignKey(User, on_delete = models.CASCADE)
    # room = models.ForeignKey('Room', on_delete=models.CASCADE, blank=True)
    title = models.CharField(max_length=200, blank=True)
    image = models.ImageField(upload_to='images')

    def __str__(self):
        return f"Image - {self.title}"

chat/forms.py
from django import forms
from .models import ImageUpload


class ImageForm(forms.ModelForm):
    """Form for the image model"""
    class Meta:
        model = ImageUpload
        fields = ('title', 'image')




# from django import forms
# from chat.models import Messages
# from django.contrib.auth.models import User
# from django.contrib.auth import authenticate

# class LoginForm(forms.ModelForm):
#     password = forms.CharField(label='password', widget=forms.PasswordInput)  # PasswordInput hides the the password input

#     class Meta:
#         model = User
#         fields = ('username', 'password')

#     def clean(self): # here self is form
#         if self.is_valid():
#             # this clean method runs before anything in the forms
#             username = self.cleaned_data['username']
#             password = self.cleaned_data['password']

#             if not authenticate(username=username, password=password): # here if anything in this email and password entered is wrong..then it will raise the error
#                 raise forms.ValidationError("Invalid Data")





















# class MessagesForm(forms.ModelForm):
#     class Meta:
#         model = Messages
#         fields = ('message',)
#         # widgets = {
#         #     'message': forms.TextInput(attrs={'class':'form-control', 'placeholder':'message placeholder'})
#         # }
        

chat/views.py
import pdb
import traceback
from django.shortcuts import render, redirect
from chat.models import ImageUpload, Messages, Room
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm
from django.db.models import Q
from .forms import ImageForm
from .mongo_models import *
import base64


def home(request):
    """
    Function used for showing landing page of the application.
    
    :param request: HTTP Request
    :return: HTTP Response
    """
    context = {}
    rooms_list = []
    try:
        if request.method == 'POST':
            custom_roomname = request.POST['input_roomname']
            return redirect(f'/room/{custom_roomname}')
        else:
            rooms_list = Room.objects.all()
            context['rooms_list'] = rooms_list        
    except Exception as error:
        print(error)
    return render(request, 'home.html', context)


def room(request, room_name):
    """
    Function that handles all the Chat messages for authorized users.
    
    :param request: HTTP Request
    :return: HTTP Response
    """
    context = {}
    messages = []

    room = Room.objects.filter(name=room_name).first()
    if request.user.is_authenticated:
        if room:
            # messages = Messages.objects.filter(user=request.user, room=room)
            messages = Messages.objects.filter(room=room)
        else:
            room = Room(name=room_name)
            room.save()

    context['room_name'] = room_name
    context['messages'] = messages

    return render(request, 'chatroom.html', context)


def image_upload_view(request, room_name):
    """Process images uploaded by users"""
    if request.method == 'POST':
        form = ImageForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            # Get the current instance object to display in the template
            img_obj = form.instance  # it will return the image model object
            # return render(request, 'image_upload.html', {'form': form, 'img_obj': img_obj})
            room_obj = Room.objects.filter(name=room_name).first()
            Messages.objects.create(user=request.user, message=img_obj.title, room=room_obj, image=img_obj)
            return redirect(f'/room/{room_name}/')
    else:
        form = ImageForm()
    return render(request, 'image_upload.html', {'form': form})


def signup_view(request):
    """
    Function that handles all the registration or signup part.
    
    :param request: HTTP Request
    :return: HTTP Response
    """
    context = {}

    if request.user.is_authenticated: # if the user is already authenticated
        return redirect('/')

    if request.method == 'POST':  # if user filled the form
        form = UserCreationForm(request.POST)  # passing the data's for further use

        if form.is_valid():  # this is the function of above django's UserCreatingForm
            form.save()  # saving form for further use
            username = request.POST['username']  # entered_username
            password = request.POST['password1']  # entered_password
            user = authenticate(request, username=username, password=password)

            if user:
                login(request, user)
                return redirect('/')

        else:
            print('Form is not valid!')
            return render(request, 'signup.html', {'form': form})
            
    else:
        print('First time opened')
        return render(request, 'signup.html', context)


def signin_view(request):
    """
    Function that handles signing up the users.
    
    :param request: HTTP Request
    :return: HTTP Response
    """
    context = {}
    if request.user.is_authenticated:
        return redirect('/')
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user:
            login(request, user)
            return redirect('/')
        else:
            return render(request, 'signin.html', context)
    else:
        return render(request, 'signin.html', context)


def signout_view(request):
    """
    Function that handles signing out the users.
    
    :param request: HTTP Request
    :return: HTTP Response
    """
    logout(request)
    return redirect('/')


# def room(request, room_name):
#     context = {}
#     room = Room.objects.filter(name=room_name).first()
#     # images = ImageUpload.objects.filter(name=room_name).first()
#     all_messages = []
#     all_images = []
#     if request.user.is_authenticated:
#         user = User.objects.get(username=request.user.username)
#         if room:
#             # messages = Messages.objects.filter(room=room).filter(user=user)
#             # other_messages = Messages.objects.filter(room=room).filter(~Q(user=user))
#             all_messages = Messages.objects.filter(room=room)
#             all_images = ImageUpload.objects.filter(room=room).order_by('-id')
#         else:
#             room = Room(name=room_name)
#             room.save()

#     context['room_name'] = room_name
#     context['all_messages'] = all_messages
#     context['all_images'] = all_images
#     # context['image_form'] = image_form
#     # {
#     #     'room_name': room_name,
#     #     'all_messages': all_messages,
#     #     'image_form': image_form,
#     # }
#     return render(request,'chatroom.html',context)

chat/templates/base.html
{% load static %}
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
        integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

    <title>
        {% block title %}
        {% endblock %}
    </title>
    <link rel="stylesheet" href="{% static '/style.css' %}">
    {% block head %}
    {% endblock %}

</head>
<body>
    {% comment %} <img src="{% static 'images/sitelogo.png' %}" alt="Logo"> {% endcomment %}
    <style>
        {% block stylebody %}
        {% endblock stylebody %}
    </style>
    {% block content %}

    <!-- All the contents of the application goes here... -->

    {% endblock content %}
</body>
</html>

chat/templates/chatroom.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
{% endblock head %}

{% block title %}
Chat_App | Web_Socket
{% endblock title %}
{% block content %}
{% if user.is_authenticated %}

<div class="container" >
  <div class="row d-flex justify-content-center">
    <div class="col-6">
      {% comment %} Below room is a url namespace...room_name is an view argument {% endcomment %}
      <form action="{% url 'chat:room' room_name %}" method="POST">
        {% comment %} <form action="{% url 'chat:room' %}" method="POST"> {% endcomment %}
          {% csrf_token %}
          <div class="form-group">
            <center>
              <p
                class='room-name shadow-sm'>
                <span>{{room_name}}</span> <span> - </span><span>ROOM</span>
              </p>
            </center>

            {% comment %} flex-direction: column-reverse; ----- It will reverse the whole div (reverse the elements inside the div if you've removed flex-direction) {% endcomment %}
            <div class="paragraph-div shadow-sm">
              <p id="chat-text"></p>

              {% for msg in messages %}
              {% if msg.user.id is request.user.id%}
                <p class='user-message'>
                  <span class="name">{{msg.user.username | capfirst}}: </span>{{msg.message}}
                </p>
                {% if msg.image %}
                  <img class="user-img" src="{{ msg.image.image.url }}" alt="{{ msg.image.title }}">
                {% endif %}
              {% else %}
                <p class='others-message'>
                  <span class="name">{{msg.user.username | capfirst}}: </span>{{msg.message}}
                </p>
                {% if msg.image %}
                  <img class="others-img" src="{{ msg.image.image.url }}" alt="{{ msg.image.title }}">
                {% endif %}
              {% endif %}
              {% endfor %}

            </div>

          </div>

          <div class="form-group">
            <input name="msg" class="form-control"
              id="input" type="text"
              placeholder="Type something here . . .">
          </div>
          <center>
          <div class='msg-img-send-button'>
            {% if room_name %}
            {% comment %} href="/room/{{ room_name }}/image_upload/" {% endcomment %}
                <a class='upload-image-button' href="{{request.get_full_path}}image_upload">
                  Upload Image
                </a>

            {% endif %}
            <button
              class='send-button'
              id="submit" type="submit">SEND
            </button>
        </div>
        </center>
        </form>
    </div>
  </div>

</div>
{{ request.user.username|json_script:"user_username" }}
{{ request.user.id|json_script:"user_id" }}
{{ room_name|json_script:"room-name" }}

{% else %}
<center>
  <h1 style='margin-top: 10px; width:fit-content; color:#2e2e2e; border-radius:1rem; background-color:#f87171; padding:1rem; font-weight:900; margin:5rem;'>
    LOGIN TO CONTINUE
  </h1>

  <p style='margin-top: 10px; width:fit-content; color:#2e2e2e; border-radius:1rem; background-color:#fff; padding:1rem;' class="text-center">Already have an account? <a style='text-decoration: none; font-weight: 800;' href="/signin">SignIn</a></p>

  <p style='margin-top: 10px; width:fit-content; color:#2e2e2e; border-radius:1rem; background-color:#fff; padding:1rem;' class="text-center">Don't have an account? <a style='text-decoration: none; font-weight:800;' href="/signup">Register</a></p>

</center>
{% endif %}

<script>
  const user_username = JSON.parse(document.getElementById('user_username').textContent);
  const user_id = JSON.parse(document.getElementById('user_id').textContent);
  document.querySelector('#submit').onclick = function (e) {
    e.preventDefault()
    //e.stopPropagation()

    const messageInputDom = document.querySelector('#input');
    const message = messageInputDom.value;

    chatSocket.send(JSON.stringify({
      'message': message,
      'username': user_username,
      'user_id': user_id,
    }));
    messageInputDom.value = '';
  };

  const roomName = JSON.parse(document.getElementById('room-name').textContent);
  // if we want to turn an json string to object then we use parse. It will convert the json string to key value pair.

  const chatSocket = new WebSocket(
    'ws://' +
    window.location.host +
    '/ws/chatt/room/' +
    roomName +
    '/'
  );

  chatSocket.onmessage = function (a) {
    const data = JSON.parse(a.data);
    console.log(data)

    document.querySelector('#chat-text').innerHTML += (
      data.username == user_username ?
        '<p class="user-message"><span class="name">' + data.username.charAt(0).toUpperCase() + data.username.slice(1) + ': ' + '</span>' + data.message + '</p>'
        :
        '<p class="others-message"><span class="name">' + data.username.charAt(0).toUpperCase() + data.username.slice(1) + ': ' + '</span>' + data.message + '</p>'
    )
  }

</script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>



<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
  integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous">
  </script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
  integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous">
  </script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
  integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous">
  </script>
{% endblock content %}

chat/templates/home.html
{% extends 'base.html' %} {% block content %} {% load static %} {% block head %}
<link rel="stylesheet" href="{% static '/home.css' %}" />
{% endblock head %}
<div class="container">
  <div class="row d-flex justify-content-center">
    <div class="main-div col-12">
      <div class="heading-div">
        <h1 class="heading">LIST OF ROOMS</h1>
      </div>
      <form method="POST">
        {% csrf_token %}
        <div class="custom-room-div" >
            <input
              type="text"
              class="form-control"
              name="input_roomname"
              required
              placeholder="Enter any room name here . . ."
            />
            <button class='custom-join'>Join</button>
        </div>  
      </form>
      <div class="list-of-rooms">
        {% for roomname in rooms_list%}
        <div class="room-div">
          <p class="room-name">{{roomname}}</p>
          <a href="/room/{{roomname}}" class="join">Join</a>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>
</div>
{% endblock content %}

chat/templates/image_upload.html
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
     {{ form.as_p }}
    <button type="submit">Upload</button>
  </form>
  
  {% if img_obj %}
    <h3>Succesfully uploaded : {{img_obj.title}}</h3>
    <img src="{{ img_obj.image.url}}" alt="connect" style="max-height:300px">
  {% endif %}

chat/templates/image_upload2.html
<!DOCTYPE html>
<html>
<body>
<form  method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <label for="img_id">Select image:</label>
    <input type="file" id="img_id" name="img_name">
    {% comment %} <input name="title_name" class="form-control" id="title_id"  type="text" placeholder="Enter Title: "> {% endcomment %}
    <button type="submit">Submit</button>
</form>


{% if request.method == "POST" %}
  <p>Successfully uploaded: {{img}}</p>
  <img width="300" src="{{ img.image.url }}" alt = 'test_img' style="max-height: 300px">
{% endif %}

{% for i in images %}
  <p>File: {{i.image}}</p>
  <img width="300" src="{{ i.image.url }}" alt = 'test_img' style="max-height: 300px">
{% endfor %}

</body>
</html>

chat/templates/index.html
Create a room by adding room name on the url.

chat/templates/signin.html
{% extends 'base.html' %}
{% block title %}SignIN{% endblock %}
{% block content %}
<center>
<div class="shadow-sm p-4 mb-auto bg-body" 
  style='width: 600px;  
      margin-top:50px; 
      height:auto;
      {% comment %} border: 1px solid ; {% endcomment %}
      border-radius:2rem;
      background: #fff;
      '>
<h1 style="font-weight:800; margin-bottom: 30px;">SIGNIN</h1>
<div class="form-group" style="background:#ffe299; border-radius:2rem; padding:0.5rem;">
<form method="POST"> 
    {% csrf_token %} 
    <div class="mt-3 container mt-4" >
        <div class="mb-3">
          <label class="form-label">Username</label>
          <input type="text" class="form-control" name="username" required id ='username_id' placeholder="Enter your username" style="width:80%; border-radius:1rem;">
        </div>
        <div class="mb-3">
          <label class="form-label">Password</label>
          <input type="password" class="form-control" name="password" required id ='password_id' placeholder="Enter your password" style="width:80%; border-radius:1rem; ">
        </div>
        <button class="btn btn-warning" style='border: 3px #2e2e2e solid; border-radius:1rem; background:#90CAF9; font-weight: 800; padding:0.7rem 2rem; margin-top:0.5rem; margin-bottom:1.5rem;'>SIGNIN</button>
        <p style='margin-top: 10px; width:fit-content; color:#2e2e2e; border-radius:1rem; background-color:#fff; padding:1rem;' class="text-center">Don't have an account? <a style='text-decoration: none; font-weight:800;' href="/signup">Register</a></p>    
</form>  
</div> 
</div>
</center>
{% endblock %}

chat/templates/signup.html
{% extends 'base.html' %}
{% block title %}Register{% endblock %}
{% block content %}
<center>
<div class="shadow-sm p-4 mb-auto bg-body" 
  style='width: 600px;  
      margin-top:50px; 
      height:auto;
      {% comment %} border: 1px solid ; {% endcomment %}
      border-radius:2rem;
      background: #fff;

      '>
<h1 style="font-weight:800; margin-bottom: 30px;">REGISTER</h1>
<div class="form-group" style="background:#ffe299; border-radius:2rem; padding:0.5rem;">
<form method="POST"> 
    {% csrf_token %}
    <div class="mt-3 container mt-4" >
        <div class="mb-3">
          <label class="form-label">Username</label>
          <input type="text" class="form-control" name="username" required id ='username_id' placeholder="Create your username" style="width:80%; border-radius:1rem;">
        </div>
        <div class="mb-3">
          <label class="form-label">Password</label>
          <input type="password" class="form-control" name="password1" required id ='password_id' placeholder="Create your password" style="width:80%; border-radius:1rem; ">
        </div>
        <div class="mb-3" >
          <label class="form-label">Password</label>
          <input type="password" class="form-control" name="password2" required id ='password_id2' placeholder="Re-enter the password" style="width:80%; border-radius:1rem; ">
        </div>
    <button class="btn btn-warning" style='border: 3px #2e2e2e solid; border-radius:1rem; background:#90CAF9; font-weight: 800; padding:0.7rem 2rem; margin-top:0.5rem; margin-bottom:1.5rem;'>REGISTER</button>
    <p style='margin-top: 10px; width:fit-content; color:#2e2e2e; border-radius:1rem; background-color:#fff; padding:1rem;' class="text-center">Already have an account? <a style='text-decoration: none; font-weight: 800;' href="/signin">SignIn</a></p>

</form>  
</div> 
</div>
</center>
{% endblock %}